Repository RookeriesDevelopment/rook-ios-sdk-rook-sdk-pod, pull requests merged in 2024-03, with the labels that each got.

#33 version 1.3.0
  RookSDK.podspec
  RookSDK.xcframework/ios-arm64/RookSDK.framework/RookSDK
Labels: bug

#34 version 1.3.1
  RookSDK.podspec
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Headers/RookSDK-Swift.h
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.abi.json
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.private.swiftinterface
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.swiftinterface
  RookSDK.xcframework/ios-arm64/RookSDK.framework/PrivacyInfo.xcprivacy
  RookSDK.xcframework/ios-arm64/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64/RookSDK.framework/_CodeSignature/CodeResources
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Headers/RookSDK-Swift.h
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.private.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.private.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/PrivacyInfo.xcprivacy
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/_CodeSignature/CodeResources
Labels: enhancement

#35 version 1.3.2
  RookSDK.podspec
  RookSDK.xcframework/Info.plist
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.abi.json
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.private.swiftinterface
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.swiftinterface
  RookSDK.xcframework/ios-arm64/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64/RookSDK.framework/_CodeSignature/CodeResources
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.private.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.private.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/_CodeSignature/CodeResources
Labels: enhancement

#36 version 1.3.3
  RookSDK.podspec
  RookSDK.xcframework/Info.plist
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Headers/RookSDK-Swift.h
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.abi.json
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.private.swiftinterface
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.swiftinterface
  RookSDK.xcframework/ios-arm64/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64/RookSDK.framework/_CodeSignature/CodeResources
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Headers/RookSDK-Swift.h
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.private.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.private.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/_CodeSignature/CodeResources
Labels: bug, enhancement
