Repository RookeriesDevelopment/rook-ios-sdk-rook-sdk-pod, pull requests merged in 2024-04, with the labels that each got.

#37 Version 1.3.4
  RookSDK.podspec
  RookSDK.xcframework/Info.plist
  RookSDK.xcframework/ios-arm64/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/RookSDK
Labels: bug

#38 Fix: objc instance for background
  RookSDK.podspec
  RookSDK.xcframework/ios-arm64/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64/RookSDK.framework/_CodeSignature/CodeResources
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/_CodeSignature/CodeResources
Labels: bug, enhancement

#39 version 1.3.6
  RookSDK.podspec
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Info.plist
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.abi.json
  RookSDK.xcframework/ios-arm64/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64/RookSDK.framework/_CodeSignature/CodeResources
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Info.plist
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/_CodeSignature/CodeResources
Labels: bug, enhancement

#40 version 1.4.0
  RookSDK.podspec
  RookSDK.xcframework/Info.plist
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Headers/RookSDK-Swift.h
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.abi.json
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.private.swiftinterface
  RookSDK.xcframework/ios-arm64/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios.swiftinterface
  RookSDK.xcframework/ios-arm64/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64/RookSDK.framework/_CodeSignature/CodeResources
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Headers/RookSDK-Swift.h
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.private.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/arm64-apple-ios-simulator.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.abi.json
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.private.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/Modules/RookSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/RookSDK
  RookSDK.xcframework/ios-arm64_x86_64-simulator/RookSDK.framework/_CodeSignature/CodeResources
Labels: enhancement, RookSDK
